name: variant_env
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.12
  - bcftools=1.20
  - binutils_impl_linux-64=2.40
  - bwa=0.7.18
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - curl=8.9.1
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gatk4=4.5.0.0
  - gcc_impl_linux-64=14.1.0
  - gfortran_impl_linux-64=14.1.0
  - giflib=5.2.2
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=14.1.0
  - harfbuzz=9.0.0
  - htslib=1.20
  - icu=75.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsanitizer=14.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - make=4.3
  - ncurses=6.5
  - openjdk=17.0.11
  - openssl=3.3.1
  - pango=1.54.0
  - pcre2=10.44
  - perl=5.32.1
  - picard=3.2.0
  - pip=24.2
  - pixman=0.43.2
  - pthread-stubs=0.4
  - python=3.12.5
  - r-base=4.4.1
  - readline=8.2
  - samtools=1.20
  - sed=4.8
  - setuptools=72.1.0
  - snpeff=5.2
  - sysroot_linux-64=2.17
  - tassel=5.2.89
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2024a
  - vcftools=0.1.16
  - wheel=0.44.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.5
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
